name: Java CI with Automatic Version Increment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Increment patch version
      run: |
        # Get current version from pom.xml
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout || echo "1.0.0")
        echo "Current version: $current_version"
        
        # Use 1.0.0 if no version is set
        if [[ -z "$current_version" || "$current_version" == *"-SNAPSHOT" ]]; then
          current_version="1.0.0"
        fi

        # Extract base version and patch number
        base_version=${current_version%.*}
        patch_version=${current_version##*.}

        # Increment patch version
        new_patch_version=$((patch_version + 1))
        new_version="$base_version.$new_patch_version"

        # Update the pom.xml with the new version
        mvn versions:set -DnewVersion=$new_version -q
        mvn versions:commit -q

        echo "New version set to: $new_version"

    - name: Commit version increment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add pom.xml
        git commit -m "Increment version to $new_version"
        git push

    - name: Build with Maven
      run: mvn clean package
