name: Java CI with Automatic Version Increment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Auto-increment the version number
      id: version
      uses: Kaven-Universe/github-action-auto-increment-version@v1
      with:
        file: "pom.xml"

    - name: Commit version increment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add pom.xml
        git commit -m "Increment version from ${{ steps.version.outputs.oldVersion }} to ${{ steps.version.outputs.newVersion }}"
        git push

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker Image
      run: |
        echo "Building Docker image..."
        docker build . -f Dockerfile -t rebachi/githuub-actions:latest

    - name: Login to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Push Docker Image
      run: docker push rebachi/githuub-actions:latest
